"""empty message

Revision ID: 930a1774d5bc
Revises: fbb05ed0bdae
Create Date: 2025-11-01 00:33:26.472635

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "930a1774d5bc"
down_revision: Union[str, Sequence[str], None] = "fbb05ed0bdae"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "uq_post_tag", "association", ["post_id", "tag_id"]
    )
    op.add_column("posts", sa.Column("read_time", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("posts", "read_time")
    op.drop_constraint("uq_post_tag", "association", type_="unique")
    # ### end Alembic commands ###
